# Generated by Django 2.0 on 2018-01-09 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yummyPI', '0003_categories_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='category_name',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='yummyPI.Categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_by',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
